# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setWindowModality(QtCore.Qt.WindowModal)
        Login.resize(447, 468)
        Login.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(Login)
        self.verticalLayout.setSpacing(-1)
        self.verticalLayout.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(Login)
        self.label_3.setMaximumSize(QtCore.QSize(128, 128))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/res/shotgun_logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName("formLayout")
        self.login_label = QtGui.QLabel(Login)
        self.login_label.setObjectName("login_label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.login_label)
        self.login = QtGui.QLineEdit(Login)
        self.login.setObjectName("login")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.login)
        self.password_label = QtGui.QLabel(Login)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.password_label)
        self.script_label = QtGui.QLabel(Login)
        self.script_label.setObjectName("script_label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.script_label)
        self.key_label = QtGui.QLabel(Login)
        self.key_label.setObjectName("key_label")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.key_label)
        self.password = QtGui.QLineEdit(Login)
        self.password.setEchoMode(QtGui.QLineEdit.Password)
        self.password.setObjectName("password")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.password)
        self.script = QtGui.QLineEdit(Login)
        self.script.setObjectName("script")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.script)
        self.key = QtGui.QLineEdit(Login)
        self.key.setObjectName("key")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.key)
        self.site_label = QtGui.QLabel(Login)
        self.site_label.setObjectName("site_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.site_label)
        self.site = QtGui.QLineEdit(Login)
        self.site.setObjectName("site")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.site)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.frame = QtGui.QFrame(Login)
        self.frame.setStyleSheet("color: rgb(174, 35, 40)")
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.message = QtGui.QLabel(self.frame)
        self.message.setText("")
        self.message.setAlignment(QtCore.Qt.AlignCenter)
        self.message.setWordWrap(True)
        self.message.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.message.setObjectName("message")
        self.horizontalLayout_3.addWidget(self.message)
        self.verticalLayout.addWidget(self.frame)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.remember_me = QtGui.QCheckBox(Login)
        self.remember_me.setChecked(True)
        self.remember_me.setObjectName("remember_me")
        self.horizontalLayout_5.addWidget(self.remember_me)
        self.buttonBox = QtGui.QDialogButtonBox(Login)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.login_label.setBuddy(self.login)
        self.password_label.setBuddy(self.password)
        self.script_label.setBuddy(self.script)
        self.key_label.setBuddy(self.key)
        self.site_label.setBuddy(self.site)

        self.retranslateUi(Login)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Login.reject)
        QtCore.QMetaObject.connectSlotsByName(Login)
        Login.setTabOrder(self.site, self.login)
        Login.setTabOrder(self.login, self.password)
        Login.setTabOrder(self.password, self.script)
        Login.setTabOrder(self.script, self.key)

    def retranslateUi(self, Login):
        Login.setWindowTitle(QtGui.QApplication.translate("Login", "Shotgun Login", None, QtGui.QApplication.UnicodeUTF8))
        self.login_label.setToolTip(QtGui.QApplication.translate("Login", "The username to log into shotgun with.", None, QtGui.QApplication.UnicodeUTF8))
        self.login_label.setText(QtGui.QApplication.translate("Login", "Login:", None, QtGui.QApplication.UnicodeUTF8))
        self.login.setPlaceholderText(QtGui.QApplication.translate("Login", "login", None, QtGui.QApplication.UnicodeUTF8))
        self.password_label.setToolTip(QtGui.QApplication.translate("Login", "The password for the account to log into.", None, QtGui.QApplication.UnicodeUTF8))
        self.password_label.setText(QtGui.QApplication.translate("Login", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.script_label.setToolTip(QtGui.QApplication.translate("Login", "A script name to use when connecting to Shotgun.", None, QtGui.QApplication.UnicodeUTF8))
        self.script_label.setText(QtGui.QApplication.translate("Login", "Script:", None, QtGui.QApplication.UnicodeUTF8))
        self.key_label.setToolTip(QtGui.QApplication.translate("Login", "The key for the script to connect to Shotgun as.", None, QtGui.QApplication.UnicodeUTF8))
        self.key_label.setText(QtGui.QApplication.translate("Login", "Key:", None, QtGui.QApplication.UnicodeUTF8))
        self.password.setPlaceholderText(QtGui.QApplication.translate("Login", "p@ssw0rd", None, QtGui.QApplication.UnicodeUTF8))
        self.script.setPlaceholderText(QtGui.QApplication.translate("Login", "ScriptName", None, QtGui.QApplication.UnicodeUTF8))
        self.key.setPlaceholderText(QtGui.QApplication.translate("Login", "1234567890", None, QtGui.QApplication.UnicodeUTF8))
        self.site_label.setToolTip(QtGui.QApplication.translate("Login", "The full url for the Shotgun site to connect to, ncluding the https://", None, QtGui.QApplication.UnicodeUTF8))
        self.site_label.setText(QtGui.QApplication.translate("Login", "Site:", None, QtGui.QApplication.UnicodeUTF8))
        self.site.setPlaceholderText(QtGui.QApplication.translate("Login", "https://mysite.shotgunstudio.com", None, QtGui.QApplication.UnicodeUTF8))
        self.remember_me.setText(QtGui.QApplication.translate("Login", "Remember me", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
