# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'no_apps_installed_overlay.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from sgtk.platform.qt import QtCore, QtGui

class Ui_NoAppsInstalledOverlay(object):
    def setupUi(self, NoAppsInstalledOverlay):
        NoAppsInstalledOverlay.setObjectName("NoAppsInstalledOverlay")
        NoAppsInstalledOverlay.resize(425, 540)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NoAppsInstalledOverlay.sizePolicy().hasHeightForWidth())
        NoAppsInstalledOverlay.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(NoAppsInstalledOverlay)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.icon_rows = QtGui.QVBoxLayout()
        self.icon_rows.setObjectName("icon_rows")
        self.verticalLayout.addLayout(self.icon_rows)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.main_label = QtGui.QLabel(NoAppsInstalledOverlay)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_label.sizePolicy().hasHeightForWidth())
        self.main_label.setSizePolicy(sizePolicy)
        self.main_label.setStyleSheet("font-size: 20px;")
        self.main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label.setObjectName("main_label")
        self.verticalLayout.addWidget(self.main_label)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sub_label_1 = QtGui.QLabel(NoAppsInstalledOverlay)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sub_label_1.sizePolicy().hasHeightForWidth())
        self.sub_label_1.setSizePolicy(sizePolicy)
        self.sub_label_1.setStyleSheet("font-size: 18px; color: #888888")
        self.sub_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.sub_label_1.setObjectName("sub_label_1")
        self.verticalLayout_2.addWidget(self.sub_label_1)
        self.sub_label_2 = QtGui.QLabel(NoAppsInstalledOverlay)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sub_label_2.sizePolicy().hasHeightForWidth())
        self.sub_label_2.setSizePolicy(sizePolicy)
        self.sub_label_2.setStyleSheet("font-size: 18px; color: #888888")
        self.sub_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sub_label_2.setObjectName("sub_label_2")
        self.verticalLayout_2.addWidget(self.sub_label_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 200, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.link_label = QtGui.QLabel(NoAppsInstalledOverlay)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.link_label.sizePolicy().hasHeightForWidth())
        self.link_label.setSizePolicy(sizePolicy)
        self.link_label.setStyleSheet("color: #888888")
        self.link_label.setAlignment(QtCore.Qt.AlignCenter)
        self.link_label.setObjectName("link_label")
        self.verticalLayout_3.addWidget(self.link_label)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)

        self.retranslateUi(NoAppsInstalledOverlay)
        QtCore.QMetaObject.connectSlotsByName(NoAppsInstalledOverlay)

    def retranslateUi(self, NoAppsInstalledOverlay):
        NoAppsInstalledOverlay.setWindowTitle(QtGui.QApplication.translate("NoAppsInstalledOverlay", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.main_label.setText(QtGui.QApplication.translate("NoAppsInstalledOverlay", "We couldn\'t find anything to launch.", None, QtGui.QApplication.UnicodeUTF8))
        self.sub_label_1.setText(QtGui.QApplication.translate("NoAppsInstalledOverlay", "Install a supported", None, QtGui.QApplication.UnicodeUTF8))
        self.sub_label_2.setText(QtGui.QApplication.translate("NoAppsInstalledOverlay", "application to start using it with Shotgun.", None, QtGui.QApplication.UnicodeUTF8))
        self.link_label.setText(QtGui.QApplication.translate("NoAppsInstalledOverlay", "Click here to find out how to configure this screen.", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
