# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'systray.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_SystemTrayWindow(object):
    def setupUi(self, SystemTrayWindow):
        SystemTrayWindow.setObjectName("SystemTrayWindow")
        SystemTrayWindow.resize(396, 727)
        SystemTrayWindow.setDockNestingEnabled(True)
        SystemTrayWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks|QtGui.QMainWindow.ForceTabbedDocks)
        self.center = QtGui.QWidget(SystemTrayWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.center.sizePolicy().hasHeightForWidth())
        self.center.setSizePolicy(sizePolicy)
        self.center.setObjectName("center")
        self.border_layout = QtGui.QVBoxLayout(self.center)
        self.border_layout.setObjectName("border_layout")
        self.header_frame = QtGui.QFrame(self.center)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.header_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.header_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.header_frame.setLineWidth(2)
        self.header_frame.setMidLineWidth(0)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shotgun_icon_label = QtGui.QLabel(self.header_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotgun_icon_label.sizePolicy().hasHeightForWidth())
        self.shotgun_icon_label.setSizePolicy(sizePolicy)
        self.shotgun_icon_label.setMinimumSize(QtCore.QSize(36, 36))
        self.shotgun_icon_label.setMaximumSize(QtCore.QSize(36, 36))
        self.shotgun_icon_label.setText("")
        self.shotgun_icon_label.setPixmap(QtGui.QPixmap(":/res/shotgun_logo.png"))
        self.shotgun_icon_label.setScaledContents(True)
        self.shotgun_icon_label.setMargin(5)
        self.shotgun_icon_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.shotgun_icon_label.setObjectName("shotgun_icon_label")
        self.horizontalLayout.addWidget(self.shotgun_icon_label)
        self.shotgun_desktop_label = QtGui.QLabel(self.header_frame)
        font = QtGui.QFont()
        self.shotgun_desktop_label.setFont(font)
        self.shotgun_desktop_label.setMouseTracking(False)
        self.shotgun_desktop_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.shotgun_desktop_label.setObjectName("shotgun_desktop_label")
        self.horizontalLayout.addWidget(self.shotgun_desktop_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.settings_button = QtGui.QToolButton(self.header_frame)
        self.settings_button.setMinimumSize(QtCore.QSize(36, 36))
        self.settings_button.setMaximumSize(QtCore.QSize(36, 36))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_button.setIcon(icon)
        self.settings_button.setIconSize(QtCore.QSize(32, 32))
        self.settings_button.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.settings_button.setAutoRaise(True)
        self.settings_button.setArrowType(QtCore.Qt.NoArrow)
        self.settings_button.setObjectName("settings_button")
        self.horizontalLayout.addWidget(self.settings_button)
        self.border_layout.addWidget(self.header_frame)
        self.line = QtGui.QFrame(self.center)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.border_layout.addWidget(self.line)
        self.projects = QtGui.QListView(self.center)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projects.sizePolicy().hasHeightForWidth())
        self.projects.setSizePolicy(sizePolicy)
        self.projects.setMaximumSize(QtCore.QSize(16777215, 128))
        self.projects.setFrameShape(QtGui.QFrame.Panel)
        self.projects.setFrameShadow(QtGui.QFrame.Plain)
        self.projects.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.projects.setProperty("showDropIndicator", False)
        self.projects.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.projects.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.projects.setMovement(QtGui.QListView.Static)
        self.projects.setFlow(QtGui.QListView.LeftToRight)
        self.projects.setProperty("isWrapping", False)
        self.projects.setResizeMode(QtGui.QListView.Fixed)
        self.projects.setLayoutMode(QtGui.QListView.Batched)
        self.projects.setSpacing(3)
        self.projects.setViewMode(QtGui.QListView.IconMode)
        self.projects.setUniformItemSizes(True)
        self.projects.setObjectName("projects")
        self.border_layout.addWidget(self.projects)
        self.tabs = QtGui.QTabWidget(self.center)
        self.tabs.setUsesScrollButtons(True)
        self.tabs.setMovable(True)
        self.tabs.setObjectName("tabs")
        self.border_layout.addWidget(self.tabs)
        SystemTrayWindow.setCentralWidget(self.center)

        self.retranslateUi(SystemTrayWindow)
        QtCore.QMetaObject.connectSlotsByName(SystemTrayWindow)

    def retranslateUi(self, SystemTrayWindow):
        SystemTrayWindow.setWindowTitle(QtGui.QApplication.translate("SystemTrayWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.shotgun_desktop_label.setText(QtGui.QApplication.translate("SystemTrayWindow", "<big>Shotgun</big>", None, QtGui.QApplication.UnicodeUTF8))
        self.settings_button.setText(QtGui.QApplication.translate("SystemTrayWindow", "...", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
